In [110]:
from collections import defaultdict
import numpy as np

In [16]:
x = np.random.randint(0, 10, size=5)
x

array([5, 3, 6, 0, 8])

## Bubble Sort

Recursively loop throught the array, looking at items in pairs. If the first item is larger than the second, swap them. Continue this process until there are no swaps made (array is sorted).

In [12]:
def bubble(x):
    madeSwap = True
    while madeSwap:
        madeSwap = False
        for i in range(len(x) - 1):
            if x[i] > x[i+1]:
                x[i], x[i+1] = x[i+1], x[i]
                madeSwap = True
    return x

In [41]:
print(x)
print(bubble(x.copy()))

[5 3 6 0 8]
[0 3 5 6 8]


## Selection Sort

Repeatedly loop through the array, looking for the smallest value. Swap the smallest value with the first location in the unsorted partition.

In [62]:
def selection(x):
    for unsort_ptr in range(len(x)):
        min_ptr = unsort_ptr
        for i in range(unsort_ptr, len(x)):
            if x[i] < x[min_ptr]:
                min_ptr = i
        x[unsort_ptr], x[min_ptr] = x[min_ptr], x[unsort_ptr]
    return x

In [63]:
print(x)
print(selection(x.copy()))

[5 3 6 0 8]
[0 3 5 6 8]


## Insertion Sort

Loop through the array. For each item, loop back through the rest to find it's location in the "sorted" partition.

In [36]:
def insertion(x):
    for i in range(1, len(x)):
        for j in range(i, 0, -1):
            if x[j] < x[j-1]:
                x[j], x[j-1] = x[j-1], x[j]
            else:
                break
    return x

In [39]:
print(x)
print(insertion(x.copy()))

[5 3 6 0 8]
[0 3 5 6 8]


## Merge Sort

Recursively split the array into pieces and then merge neighboring chunks.

In [68]:
def merge(x):
    result = np.zeros(len(x), dtype=int)
    if len(x) < 2:
        return x
    mid = len(x) // 2
    a = merge(x[:mid])
    b = merge(x[mid:])
    i, j, c = 0, 0, 0
    while (i < len(a)) or (j < len(b)):
        if (i < len(a)) and (j < len(b)):
            if a[i] <= b[j]:
                result[c] = a[i]
                i += 1
            else:
                result[c] = b[j]
                j += 1
        elif i < len(a):
            result[c] = a[i]
            i += 1
        else:
            result[c] = b[j]
            j += 1
        c += 1
    return result

In [69]:
print(x)
print(merge(x.copy()))

[5 3 6 0 8]
[0 3 5 6 8]


## Radix Sort

Create $k$ bins and sort each number into the bins, one digit at a time

In [165]:
def radix(x, k=10):
    for n in range(int(np.log10(x).max())+1):
        result = []
        bins = {i: [] for i in range(k)}
        digit = 10 ** n
        for i in x:
            bins[i//digit % 10].append(i)
        for val in bins.values():
            result.extend(val)
        x = result[:]
    return x

In [166]:
b = np.random.randint(0, int(1e6), 10)
print(radix(b))
print(np.sort(b))

[19591, 193158, 225212, 235289, 320257, 557539, 670035, 681777, 919574, 929334]
[ 19591 193158 225212 235289 320257 557539 670035 681777 919574 929334]


## Quick Sort

Set first element in unsorted section as the pivot. Go through rest of list moving items smaller than the pivot in front of those larger than the pivot. Then swap the pivot with the last smaller than item. Repeat for each unsorted section.

In [202]:
def quick(x):
    if len(x) < 2:
        return x
    pivot = 0
    swap = 1
    last_small = 0
    for i in range(swap, len(x)):
        if x[i] < x[pivot]:
            x[swap], x[i] = x[i], x[swap]
            last_small = swap
            swap += 1    
    x[pivot], x[last_small] = x[last_small], x[pivot]
    x[:swap] = quick(x[:swap])
    x[swap:] = quick(x[swap:])
    return x

In [207]:
b = np.random.randint(0, 20, 10)
print(b)
print(quick(b.copy()))

[ 8  8  1 19 11 10 16  9  5  6]
[ 1  5  6  8  8  9 10 11 16 19]


## Heap Sort

Build heap out of the array and then use heapify to sort it